### ISSUE TITLE
Add crates.io registry support for Rust

### ISSUE THREAD

**Issue by stevenhartley** [eclipse-uprotocol/uprotocol-core-api#76]
Add to the release workflows the ability to build and publish rust artifacts that are uploaded to crates.io

**Comment by sophokles73** [comment]
> I'll need some minimal build/test to ensure there are no issues with the protos.

This could probably be done by means of a [protobuf linter](https://github.com/yoheimuta/protolint) from within a GitHub workflow?

> So then uprotocol-core-api would not publish anything to maven central, conan central, crates, pypi?

I guess not, you would simply create the version tags in the repo and have the other SDK repositories refer to them. You could probably create archives containing all the protos for easier consumption ...

**Comment by stevenhartley** [comment]
We will handle this in the language specific SDKs
